config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: :registrations }

  root 'homes#index'

  resources :users, only: [:create, :destroy, :index, :show] do
    resources :admin, only: :create
  end
  
  resources :admin, only: [:create, :destroy, :index]

  resources :curricula, only: [:index, :show]

  resources :assignments, only: [:show]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :trackable, :validatable

  attr_accessor :login

  has_many :grades, dependent: :destroy
  has_many :userplans, dependent: :destroy
  has_many :curricula, through: :userplans
  has_many :assignments, through: :curricula

  validates :username, presence: true, length: { maximum: 15 }
  validates :username, uniqueness: true, case_sensitive: false
  validates :first_name, presence: true, length: { maximum: 20 }
  validates :last_name, presence: true, length: { maximum: 25 }
  validates :password, length: { in: 8..15 }, allow_blank: false
  validates :assignment_complete, presence: true, numericality: true
  validates :assignment_complete, numericality: { greater_than: -1 }
  validate :validate_username
  validate :validate_email

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  def validate_email
    if User.where(username: email).exists?
      errors.add(:email, :invalid)
    end
  end

  def admin?
    self.admin == true
  end

  def graded?
    assignment.grade == "Pass" || assignment.grade == "Needs Work"
  end

  def complete?
    assignment.grade == "Pass"
  end

  def count
    total = 0
    @user.assignments.each do |assignment|
      if assignment.complete?
        total += 1
      end
    end
    @user.assignment_complete = total
  end

  protected

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(
        ["lower(username) = :value OR lower(email) = :value",
          { value: login.downcase }]).first
    else
      where(conditions.to_hash).first
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_admin!, only: [:index]

  def index
    @users = User.all.page params[:page]
  end

  def create
    @user = User.new
  end

  def show
    if current_user == User.find(params[:id]) || current_user.admin?
      @user = current_user
      @curricula = @user.curricula
      @assignments = @user.assignments
    else
      flash[:alert] = 'You do not have permission to access this user page.'
      redirect_to user_path(current_user)
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = 'User deleted successfully.'
    redirect_to users_path
  end

  protected

  def user_params
    params.require(:user).permit(:username, :first_name, :last_name, :email,
    :password, :login, :admin)
  end
end

app/views/users/index.html.erb
<div class="section-box large-centered small-centered large-2 small-4 columns">
  <h2 class="section-title text-center">Users</h2>
</div>
<div>
  <% @users.each do |user| %>
    <div class="large-4 medium-3 small-6 columns">
      <div class="panel text-center user-listing">
        <div id="unstyled">
          <ul>
          <p> <%= link_to user.username, user_path(user) %> </p>
          <p> <%= user.email %> </p>
              <%= button_to 'Delete', user_path(user),
              method: :delete, id: "delete-#{user.id}", class: "tiny button" %>
          <p>
            <% if user.admin? %>
              <%= button_to 'Remove Admin', admin_path(user),
                method: :delete, id: "admin-#{user.id}", class: "alert tiny button" %>
            <% else %>
              <%= button_to 'Make Admin', user_admin_index_path(user),
                method: :post, id: "admin-#{user.id}", class: "secondary tiny button" %>
            <% end %>
          </p>
        </ul>
      </div>
      </div>
    </div>
  <% end %>
</div>
<footer>
</footer>

app/views/users/show.html.erb
<div class="row">
  <div class="medium-4 columns">
    <div class="card">
      <div class="image">
        <img src="http://static.pexels.com/wp-content/uploads/2014/07/alone-clouds-hills-1909-527x350.jpg">
        <span class="title"><%= @user.username %></span>
      </div>
      <div class="content">
        <p>
          Your Badges
        </p>
      </div>
      <div class="action">
        <%- if current_user -%>
        <%= link_to "Account Settings", edit_user_registration_path(@user) %>
        <%- end -%>
      </div>
    </div>
  </div>
  <div class="medium-6 large-8 columns end">
    <div class="card">
      <div class="content">
        <span class="title">Assignments</span>
        <p>
          <row>
            <% if @assignments.size > 0 %>
            <% @assignments.each do |assignment| %>
            <%= assignment.title %>
            <%= link_to "Details", assignment_path(assignment) %>
            <% end %>
            <% else %>
            <%= "You have no assignments."  %>
            <% end %>
          <row>
        </p>
      </div>
      <div class="action">
        <a href=''>View all projects</a>
      </div>
    </div>
  <div class="card">
    <div class="content">
      <span class="title">Curricula</span>
      <p>
        <row>
          <%- if @curricula.size > 0 -%>
          <% @curricula.each do |curriculum| %>
          <%= curriculum.name %>
          <%- link_to curriculum_path(curriculum_path) -%>
          <%- end -%>
          <%- else -%>
          <%= "You have no curricula assigned."  %>
          <%- end -%>
        <row>
      </p>
    </div>
    <div class="action">
      <a href='/curricula'>View All Curricula</a>
    </div>
  </div>
</div>

app/views/users/update.html.erb
<div class="row">
  <div class="section-box text-center panel large-6 medium-8 small-12
  large-centered medium-centered small-centered columns">
    <h1 class="section-title"><%= @user.username %></h1>
  </div>
</div>
<% if current_user == @user %>
  <div class="row content text-center">
    <button data-remote="true" class="round info button button-edit-form">Account Settings</button>
    <div class="editform">
      <div class="account-box">
        <div class="account-settings clearfix">
          <%= form_for(@user, url: registration_path(@user), html: { method: :put }, class: "settings-form") do |f| %>
            <fieldset>
              <legend>Account Settings</legend>
              <div>
                <div class="large-6 columns">
                  <div class="field">
                    <%= f.label :first_name %>
                    <i>(15 characters maximum)</i><br />
                    <%= f.text_field :first_name %>
                  </div>
                  <div class="field">
                    <%= f.label :last_name %>
                    <i>(15 characters maximum)</i><br />
                    <%= f.text_field :last_name %>
                  </div>
                </div>
                <div class="large-6 columns">
                  <div class="field">
                    <%= f.label :username %>
                    <i>(15 characters maximum)</i><br />
                    <%= f.text_field :username %>
                  </div>
                </div>
                <div class="large-6 columns">
                  <div class="field">
                    <%= f.label :email %><br />
                    <%= f.email_field :email, autofocus: true %>
                  </div>
                </div>
              </div>
              <div>
                <div class="large-6 columns">
                  <div class="field">
                    <%= f.label :password %>
                    <% if @minimum_password_length %>
                    <em>(<%= @minimum_password_length %> characters minimum)</em>
                    <% end %><br />
                    <%= f.password_field :password, autocomplete: "off" %>
                  </div>
                </div>
                <div class="large-6 columns">
                  <div class="field">
                    <%= f.label :password_confirmation %><br />
                    <%= f.password_field :password_confirmation, autocomplete: "off" %>
                  </div>
                </div>
              </div>

              <div class="field">
                <%= f.label :current_password %> <i>** we need your current password to confirm your changes **</i>
                <%= f.password_field :current_password, autocomplete: "off" %>
              </div>
              <div class="actions">
                <ul class="right button-group round even-2 large-4 medium-8 small-12 columns">
                  <li><%= link_to "Back", :back, class: "small secondary button" %></li>
                  <li><%= f.submit "Update", class: "small button" %></li>
                </ul>
              </div>
            </fieldset>
          <% end %>
        </div>
        <div class="cancel-account">
          <p>
            Unhappy?
            <%= button_to "Cancel my account", registration_path(@user), data: { confirm: "Are you sure?" }, method: :delete, class: "button alert round" %>
          </p>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  </div>
</div>