config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: :registrations }

  root 'homes#index'

  resources :users, only: [:create, :destroy, :index, :show] do
    resources :admin, only: :create
  end
  
  resources :admin, only: [:create, :destroy, :index]

  resources :curricula, only: [:index, :show]

  resources :assignments, only: [:show]
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/views/homes/index.html.erb
<div class="row">
  <div class="searchbox">
    <script>
    (function() {
      var cx = '003808932512534615240:qpvh1uzjbjg';
      var gcse = document.createElement('script');
      gcse.type = 'text/javascript';
      gcse.async = true;
      gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
          '//cse.google.com/cse.js?cx=' + cx;
      var s = document.getElementsByTagName('script')[0];
      s.parentNode.insertBefore(gcse, s);
      })();
     </script>
     <gcse:search></gcse:search>
   </div>
  <div class="large-12 columns">
    <div class="large-centered small-centered
     large-12 medium-8 small-4 columns">
        <h2 class="splash-body">
          Come learn to code, and see other users' projects!
        </h2>
        <div id="curricula-link">
          <img class="panel large-centered medium-centered small-centered large-12 medium-8 small-4 columns" src="images/kidcoders.png">
          <h3 class="curricula">
          <%= link_to "View Curricula", curricula_path %>
          </h3>
        </div>
    </div>
  </div>
</div>