config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: :registrations }

  root 'homes#index'

  resources :users, only: [:create, :destroy, :index, :show] do
    resources :admin, only: :create
  end
  
  resources :admin, only: [:create, :destroy, :index]

  resources :curricula, only: [:index, :show]

  resources :assignments, only: [:show]
end

app/views/layouts/_topbar.html.erb
<div class="fixed">
  <nav class="top-bar" data-topbar>
    <ul class="title-area">
      <li class="name">
        <h1>
          <a href="/">
            Kids Who Code
          </a>
        </h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
    </ul>
    <section class="top-bar-section">
      <ul class="right">
        <% if current_user && current_user.admin? %>
          <li id="users-index"><%= link_to "View All Users", users_path %></li>
          <li id="profile"><%= link_to "My Profile", user_path(current_user) %></li>
          <li id="sign-out"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- elsif current_user -%>
          <li id="profile"><%= link_to "My Profile", user_path(current_user) %></li>
          <li id="sign-out"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li id="sign-up"><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li id="sign-in"><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
    
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
  <meta name="theme-color" content="#ffffff">
  <link rel="manifest" href="/manifest.json">
  <%= favicon_link_tag 'apple-icon-57x57.png' %>
  <%= favicon_link_tag 'apple-icon-60x60.png' %>
  <%= favicon_link_tag 'apple-icon-72x72.png' %>
  <%= favicon_link_tag 'apple-icon-76x76.png' %>
  <%= favicon_link_tag 'apple-icon-114x114.png' %>
  <%= favicon_link_tag 'apple-icon-120x120.png' %>
  <%= favicon_link_tag 'apple-icon-144x144.png' %>
  <%= favicon_link_tag 'apple-icon-152x152' %>
  <%= favicon_link_tag 'apple-icon-180x180' %>
  <%= favicon_link_tag 'android-icon-192x192.png' %>
  <%= favicon_link_tag 'favicon-32x32.png' %>
  <%= favicon_link_tag 'favicon-96x96.png' %>
  <%= favicon_link_tag 'favicon-16x16.png' %>
  <title>Kids Who code</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag :modernizr %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/topbar" %>
  <link href='https://fonts.googleapis.com/css?family=Miltonian+Tattoo' rel='stylesheet' type='text/css'>
  <%- flash.each do |key, value| -%>
  <div data-alert class="alert-box large-12 medium-8 <%= key %> round">
    <%= value %>
    <a href="" class="close">&times;</a>
    </div>
  <%- end -%>

  <section class="main">
    <%= yield %>
  </section>
  <%= javascript_include_tag :application %>
  <%= yield :extra_footer %>
<script>
  function sideNav() {
    if ($(window).width() < 769) {
      $('.off-canvas-wrap').removeClass('move-right');
      $('.left-off-canvas-toggle').show();
    } else {
      $('.off-canvas-wrap').addClass('move-right');
      $('.left-off-canvas-toggle').hide();
    }
  }
  $(window).resize(function() {
    sideNav();
  });
</script>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
  <meta name="theme-color" content="#ffffff">
  <link rel="manifest" href="/manifest.json">
  <%= favicon_link_tag 'apple-icon-57x57.png' %>
  <%= favicon_link_tag 'apple-icon-60x60.png' %>
  <%= favicon_link_tag 'apple-icon-72x72.png' %>
  <%= favicon_link_tag 'apple-icon-76x76.png' %>
  <%= favicon_link_tag 'apple-icon-114x114.png' %>
  <%= favicon_link_tag 'apple-icon-120x120.png' %>
  <%= favicon_link_tag 'apple-icon-144x144.png' %>
  <%= favicon_link_tag 'apple-icon-152x152' %>
  <%= favicon_link_tag 'apple-icon-180x180' %>
  <%= favicon_link_tag 'android-icon-192x192.png' %>
  <%= favicon_link_tag 'favicon-32x32.png' %>
  <%= favicon_link_tag 'favicon-96x96.png' %>
  <%= favicon_link_tag 'favicon-16x16.png' %>
  <title>Kids Who code</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag :modernizr %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/topbar" %>
  <link href='https://fonts.googleapis.com/css?family=Miltonian+Tattoo' rel='stylesheet' type='text/css'>
  <%- flash.each do |key, value| -%>
    <div data-alert class="alert-box large-12 medium-8 <%= key %> round">
      <%= value %>
      <a href="" class="close">&times;</a>
    </div>
  <%- end -%>
  <section class="main">
    <%= yield %>
  </section>
  <%= javascript_include_tag :application %>
  <%= yield :extra_footer %>
<script>
  function sideNav() {
    if ($(window).width() < 769) {
      $('.off-canvas-wrap').removeClass('move-right');
      $('.left-off-canvas-toggle').show();
    } else {
      $('.off-canvas-wrap').addClass('move-right');
      $('.left-off-canvas-toggle').hide();
    }
  }

  $(window).resize(function() {
    sideNav();
  });
</script>
</body>
</html>

app/views/layouts/homes.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta clss="logo" name="msapplication-TileImage" content="/ms-icon-144x144.png">
  <meta name="theme-color" content="#ffffff">
  <link rel="manifest" href="/manifest.json">
  <%= favicon_link_tag 'apple-icon-57x57.png' %>
  <%= favicon_link_tag 'apple-icon-60x60.png' %>
  <%= favicon_link_tag 'apple-icon-72x72.png' %>
  <%= favicon_link_tag 'apple-icon-76x76.png' %>
  <%= favicon_link_tag 'apple-icon-114x114.png' %>
  <%= favicon_link_tag 'apple-icon-120x120.png' %>
  <%= favicon_link_tag 'apple-icon-144x144.png' %>
  <%= favicon_link_tag 'apple-icon-152x152' %>
  <%= favicon_link_tag 'apple-icon-180x180' %>
  <%= favicon_link_tag 'android-icon-192x192.png' %>
  <%= favicon_link_tag 'favicon-32x32.png' %>
  <%= favicon_link_tag 'favicon-96x96.png' %>
  <%= favicon_link_tag 'favicon-16x16.png' %>
  <title>Kids Who code</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <link href='http://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Miltonian+Tattoo' rel='stylesheet' type='text/css'>
  <%- flash.each do |key, value| -%>
    <div class="large-12 alert-box <%= key %>">
      <%= value %>
    </div>
  <%- end -%>
  <section class="main">
    <%= yield %>
  </section>
  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>